name: Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [master]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.21
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install PhantomJS
        run: yarn global add phantomjs-prebuilt --unsafe-perm

      - name: run tests
        run: yarn run ember test
